### ISSUE TITLE
[Feature Request]Table组件标题已经支持行列合并，内容列表有没有计划支持行和列的自定义合并？？？

### ISSUE THREAD

**Issue by hujinya** [view-design/ViewUI#13]
### What problem does this feature solve?
目前遇到这种需求，只能手动重新去自己画表格，希望table组件能支持内容列表的行和列的自定义合并显示

### What does the proposed API look like?
element ui已经支持了，希望能实现同样的功能

**Comment by icarusion** [comment]
4.0 已支持，查看文档。

**Comment by hujinya** [comment]
已经看到了，谢谢
有个建议，在合并行后鼠标高亮能否包含后面的多行，这样感觉更符合实际使用场景
