### ISSUE TITLE
[Bug Report]iview4.0 表格拖动功能显示问题

### ISSUE THREAD

**Issue by Duanxy835** [view-design/ViewUI#15]
### Environment
win10，vue2.6

### Reproduction link
[https://www.iviewui.com/components/table#TZTZLK](https://www.iviewui.com/components/table#TZTZLK)

### Steps to reproduce
iview4.0 快速拖动表格列会显示

### What is expected?
表格拖动只会改变列的宽度

### What is actually happening?
表格宽度会错乱

![image](https://user-images.githubusercontent.com/33226907/66532980-eba05400-eb43-11e9-9288-48adcd703d50.png)

**Comment by icarusion** [comment]
#18
