### ISSUE TITLE
[Bug Report]Tabs面板大小未能自动适应当前选项卡的内容。

### ISSUE THREAD

**Issue by zhaojh329** [view-design/ViewUI#163]
### Environment
win10/Google Chrome 78.0.3904.97/vue 2.6

### Reproduction link
[https://run.iviewui.com/gaY2botB](https://run.iviewui.com/gaY2botB)

### Steps to reproduce
无

### What is expected?
Tabs面板的大小自动适应当前选项卡

### What is actually happening?
Tabs面板大小始终是以最大的面板为准

**Comment by RiCTT** [comment]
emm，2022年的我也遇到了

看了一下issue是2019年的了，，看来这是一个feature而不是bug；

看了下样式布局：TabPane的显示隐藏依赖的是css的visibility，所以容器的高度始终是TabPane中最高的那个

尝试解决：参考下element-ui的display去做显示隐藏

**Comment by Jack-An** [comment]
不得不说这个组件的实现有点神奇
