### ISSUE TITLE
[Bug Report]Poptip和时间组件使用选择年、月会关闭Poptip问题

### ISSUE THREAD

**Issue by aixi134** [view-design/ViewUI#182]
### Environment
最新版本

### Reproduction link
[https://run.iviewui.com/dXw81dTu](https://run.iviewui.com/dXw81dTu)

### Steps to reproduce
点击"click"按钮，选择时间中的月或者年，选中一个值之后会关闭Poptip父窗体

### What is expected?
不关闭父窗体，完整选择时间

### What is actually happening?
理论上不会关闭父窗体，实际无法正常使用

**Comment by aixi134** [comment]
现在还存在，官方人员是否在关注？

**Comment by SONGHUIJUN** [comment]
你好，现在解决了吗？我在view-design@4.0.2中直接使用DatePicker也出现这个问题了

**Comment by aixi134** [comment]
官网最新的还是出现这个问题，我换了个方式解决的。使用Dropdown&nbsp;自定义实现的





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"SONGHUIJUN"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月8日(星期三) 上午10:07
收件人:&nbsp;"view-design/ViewUI"<ViewUI@noreply.github.com&gt;;
抄送:&nbsp;"张家宾"<1344883940@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [view-design/ViewUI] [Bug Report]Poptip和时间组件使用选择年、月会关闭Poptip问题 (#182)




你好，现在解决了吗？我在view-design@4.0.2中直接使用DatePicker也出现这个问题了

**Comment by SONGHUIJUN** [comment]
谢谢！
我刚才发现我这边问题还不太一样，
直接用datepicker组件的时候，选择年或者月的时候日期弹框会消失！
发件人： aixi134
发送时间： 2020-01-08 10:17
收件人： view-design/ViewUI
抄送： SONGHUIJUN; Comment
主题： Re: [view-design/ViewUI] [Bug Report]Poptip和时间组件使用选择年、月会关闭Poptip问题 (#182)
官网最新的还是出现这个问题，我换了个方式解决的。使用Dropdown&nbsp;自定义实现的 





------------------&nbsp;原始邮件&nbsp;------------------ 
发件人:&nbsp;"SONGHUIJUN"<notifications@github.com&gt;; 
发送时间:&nbsp;2020年1月8日(星期三) 上午10:07 
收件人:&nbsp;"view-design/ViewUI"<ViewUI@noreply.github.com&gt;; 
抄送:&nbsp;"张家宾"<1344883940@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 
主题:&nbsp;Re: [view-design/ViewUI] [Bug Report]Poptip和时间组件使用选择年、月会关闭Poptip问题 (#182) 




你好，现在解决了吗？我在view-design@4.0.2中直接使用DatePicker也出现这个问题了

**Comment by aixi134** [comment]
> 谢谢！ 我刚才发现我这边问题还不太一样， 直接用datepicker组件的时候，选择年或者月的时候日期弹框会消失！ 发件人： aixi134 发送时间： 2020-01-08 10:17 收件人： view-design/ViewUI 抄送： SONGHUIJUN; Comment 主题： Re: [view-design/ViewUI] [Bug Report]Poptip和时间组件使用选择年、月会关闭Poptip问题 (#182) 官网最新的还是出现这个问题，我换了个方式解决的。使用Dropdown&nbsp;自定义实现的
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"SONGHUIJUN"<notifications@github.com&gt;; 发送时间:&nbsp;2020年1月8日(星期三) 上午10:07 收件人:&nbsp;"view-design/ViewUI"<ViewUI@noreply.github.com&gt;; 抄送:&nbsp;"张家宾"<1344883940@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [view-design/ViewUI] [Bug Report]Poptip和时间组件使用选择年、月会关闭Poptip问题 (#182) 你好，现在解决了吗？我在view-design@4.0.2中直接使用DatePicker也出现这个问题了 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
