### ISSUE TITLE
iview的Table组件的draggable属性不兼容IE11 

### ISSUE THREAD

**Issue by yuanzhian** [view-design/ViewUI#20]

**Comment by yuanzhian** [comment]
搜索网上资料，提供如下解决方案：
1、ev.dataTransfer.setData("text", ev.target.id);
data = JSON.parse(ev.dataTransfer.getData('text'));
望作者看到了，麻烦回复一下更新时间，谢谢！

**Comment by icarusion** [comment]
按要求提 issues
