### ISSUE TITLE
表头拖拽事件on-column-width-resize参数错误

### ISSUE THREAD

**Issue by klx-sentry** [view-design/ViewUI#21]
文档中描述，on-column-width-resize第一个参数为新宽度，经测试为旧宽度，查看源码可以看到
`const handleMouseUp = () => {
                        if (this.dragging) {
                            const {
                                startColumnLeft,
                                startLeft
                            } = this.dragState;

                            const finalLeft = parseInt(resizeProxy.style.left, 10);
                            const columnWidth = finalLeft - startColumnLeft;

                            const _column = table.columns.find(item => item.__id === column.__id);
                            if (_column) _column.width = columnWidth;
                            table.$emit('on-column-width-resize', column.width, startLeft - startColumnLeft, column, event);

                            document.body.style.cursor = '';
                            this.dragging = false;
                            this.draggingColumn = null;
                            this.dragState = {};

                            table.showResizeLine = false;
   }`
$emit处应该是_column.width

**Comment by icarusion** [comment]
按要求提 issues
