### ISSUE TITLE
inputNumber 控制最小值输入体验太差了

### ISSUE THREAD

**Issue by jiangleiundo** [view-design/ViewUI#220]
<InputNumber :min="9" v-model="num"><InputNumber/>
输入任意数字都会变成9，我想输入12但是刚输入1输入框中的值就成了9，这是不是个buggggg？？

**Comment by jiangleiundo** [comment]
`<InputNumber :min="9" v-model="num"><InputNumber/>`

**Comment by fairySusan** [comment]
把冒号去掉

**Comment by DebugIsFalse** [comment]
@jiangleiundo 
文档说明了 限制最大值最小值只能设置 :active-change="false"
失去焦点去设置限制
