### ISSUE TITLE
[Bug Report]Table组件使用scope-slot配合Form表单实现可编辑表格并带校验功能时，通过ref调用validate进行校验时，错误样式不展示

### ISSUE THREAD

**Issue by JobinJia** [view-design/ViewUI#279]
### Environment
macOs Catalina 10.15.2 (19C57) / Google Chrome 版本 79.0.3945.88（正式版本） （64 位）/ vue 版本2.6.11

### Reproduction link
[https://run.iviewui.com/xokOPyUe](https://run.iviewui.com/xokOPyUe)

### Steps to reproduce
打开重现链接
点击添加
鼠标移入移出姓名列时，会触发校验，错误信息并展示（功能正常）
删除该条数据，重新点击添加，再直接点击 操作列 保存，能触发校验，但校验结果样式不展示（功能异常）

### What is expected?
通过ref.validate()调用时，能正确的展示错误信息

### What is actually happening?
通过ref.validate()调用时，未能正确的展示错误信息

**Comment by Miss-Sixty** [comment]
去掉表格中fixed属性可正常显示。
