### ISSUE TITLE
[Bug Report]Bug DatePicker 

### ISSUE THREAD

**Issue by chinh12hy** [view-design/ViewUI#295]
### Environment
Google Chrome version: 79.0.3945.117.

### Reproduction link
[https://jsfiddle.net/m7rakcjb/2/](https://jsfiddle.net/m7rakcjb/2/)

### Steps to reproduce
click select DatePicker and select " << ", now time on left has no change but on right has change and ">>" is changed 2 calendar when click ">>".

### What is expected?
when i clicked "<<" and ">>" i want the only year on left or right has work not both of them.

### What is actually happening?
button select year "<<" and ">>" not working as I expected.

---
I hope to hear from gmail chinh12hy@gmail.com soon. thank you so much.

**Comment by coujk** [comment]
我也遇见了同样的问题，希望社区有人能尽快处理

**Comment by wang8254** [comment]
遇到了同样的问题，而且项目中用到了大量的这个插件，希望社区的人能尽快解决
