### ISSUE TITLE
[Bug Report]日期选择器区间筛选有Bug

### ISSUE THREAD

**Issue by wang8254** [view-design/ViewUI#309]
### Environment
win10

### Reproduction link
[https://run.iviewui.com/2GjjH1Tn](https://run.iviewui.com/2GjjH1Tn)

### Steps to reproduce
![在这里插入图片描述](https://img-blog.csdnimg.cn/20200210122551449.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3FxXzM5NTg0ODAw,size_16,color_FFFFFF,t_70)

![在这里插入图片描述](https://img-blog.csdnimg.cn/2020021012275298.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3FxXzM5NTg0ODAw,size_16,color_FFFFFF,t_70)
```javascript
<template>
    <DatePicker type="daterange" split-panels placeholder="Select date" style="width: 200px"></DatePicker>
</template>
<script>
    export default {
        
    }
</script>
```

### What is expected?
解决BUG

### What is actually happening?
先择开始时间时不能选中2020之前的年份

---
个人认为是个非常严重的BUG，因为好多项目都用的时间先择器

**Comment by icarusion** [comment]
#303
