### ISSUE TITLE
能否解决下官网点击菜单页面跳的问题

### ISSUE THREAD

**Issue by weichengdong2008** [view-design/ViewUI#31]
能否解决下官网点击菜单页面跳的问题,希望官网左边菜单保持前一次点击的视图,不然每次点击底部菜单直接跳转到顶部:

比如我点击了"tag标签"这个菜单,打开了新的页面菜单就到最上面了,影响体验,辛苦作者看看

**Comment by icarusion** [comment]
按要求提 issues

**Comment by weichengdong2008** [comment]
update
