### ISSUE TITLE
[Bug Report]DatePicker  type="daterange"   左侧年份不能切换问题

### ISSUE THREAD

**Issue by fuhanwnen** [view-design/ViewUI#327]
### Environment
谷歌浏览器 - 80.0.3987.87 / vue - 2.6.10

### Reproduction link
[https://www.iviewui.com/components/date-picker](https://www.iviewui.com/components/date-picker)

### Steps to reproduce
点击左侧 切换年份按钮 无效

### What is expected?
左侧的年份会变小

### What is actually happening?
不会改变

---
开始时间 - 结束时间  使用组件 出现 左侧年份不能切换

**Comment by icarusion** [comment]
#303
