### ISSUE TITLE
[Bug Report]DatePicker 面板不联动 

### ISSUE THREAD

**Issue by Jimmy-ajia** [view-design/ViewUI#331]
### Environment
线上

### Reproduction link
[https://www.iviewui.com/components/date-picker](https://www.iviewui.com/components/date-picker)

### Steps to reproduce
1.面板不联动 
2.点击第一个面板的<<按钮不能向前一年翻页
3.点击第一个面板的>按钮仍然是向前一个月翻页
4.点击第一个面板的>>按钮不能向下一年翻页

### What is expected?
1.点击第一个面板的<<按钮能向前一年翻页
2.点击第一个面板的>按钮是向下一个月翻页
3.点击第一个面板的>>按钮不能向下一年翻页

### What is actually happening?
1.点击第一个面板的<<按钮不能向前一年翻页
2.点击第一个面板的>按钮仍然是向前一个月翻页
3.点击第一个面板的>>按钮不能向下一年翻页

**Comment by icarusion** [comment]
#303
