### ISSUE TITLE
[Bug Report]表单动态校验结果有误

### ISSUE THREAD

**Issue by aralynn** [view-design/ViewUI#333]
### Environment
Chrome 79.0.3945.130

### Reproduction link
[https://run.iviewui.com/eXCSDf6f](https://run.iviewui.com/eXCSDf6f)

### Steps to reproduce
打开DatePicker，任意选择一个日期后点击外部空白处

### What is expected?
无错误提示

### What is actually happening?
提示“Item 1 can not be empty”

---
该例子基于官方例子[动态增减表单项](https://www.iviewui.com/components/form#DTZJBDX)修改，目前只发现DatePicker有此问题，规则去掉trigger: 'blur'后则表现正常

**Comment by heerey525** [comment]
验证规则编写错误，应指明date类型，并且change
:rules="{required: false, type: 'date', message: 'Item ' + item.index +' can not be empty', trigger: 'change'}">

**Comment by heerey525** [comment]
验证规则编写错误，应指明date类型，并且change
`:rules="{required: false, type: 'date', message: 'Item ' + item.index +' can not be empty', trigger: 'change'}">`
