### ISSUE TITLE
[Bug Report]拆分单元格后，无法使用fixed了，否则就会导致无法拆分，Iview4.0，目前发现这个Bug

### ISSUE THREAD

**Issue by zgeaw** [view-design/ViewUI#39]
### Environment
拆分单元格后，无法使用fixed了，否则就会导致无法拆分，Iview4.0，目前发现这个Bug

### Reproduction link
[https://run.iviewui.com/](https://run.iviewui.com/)

### Steps to reproduce
拆分单元格后，无法使用fixed了，否则就会导致无法拆分，Iview4.0，目前发现这个Bug

### What is expected?
拆分单元格后，无法使用fixed了，否则就会导致无法拆分，Iview4.0，目前发现这个Bug

### What is actually happening?
拆分单元格后，无法使用fixed了，否则就会导致无法拆分，Iview4.0，目前发现这个Bug

**Comment by icarusion** [comment]
请提交正确的在线示例

**Comment by zgeaw** [comment]
没有在线示例，刚升级到4.0，本地开发发现的这个bug


------------------ 原始邮件 ------------------
发件人: "Aresn"<notifications@github.com>;
发送时间: 2019年10月14日(星期一) 中午11:34
收件人: "view-design/ViewUI"<ViewUI@noreply.github.com>;
抄送: "WifeˇILoveU"<32237384@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [view-design/ViewUI] [Bug Report]拆分单元格后，无法使用fixed了，否则就会导致无法拆分，Iview4.0，目前发现这个Bug (#39)




请提交正确的在线示例

**Comment by zgeaw** [comment]
已添加在线示例
