### ISSUE TITLE
[Bug Report]Select 为多选时,无法通过 async-validator 必填验证

### ISSUE THREAD

**Issue by mick-xu** [view-design/ViewUI#408]
### Environment
chrome

### Reproduction link
[https://run.iviewui.com/sGUCYLYe](https://run.iviewui.com/sGUCYLYe)

### Steps to reproduce
参照重现链接

### What is expected?
修正这个问题

### What is actually happening?
无法使用验证

**Comment by xubowenjx** [comment]
@mick-xu 
校验的类型需要对，另外请反复查看官方文档，其实很多官网就有例子的
https://run.iviewui.com/OeIdMRP2

**Comment by mick-xu** [comment]
@xubowenjx 多谢，原来是类型的问题
