### ISSUE TITLE
[Bug Report]DatePicker 上一月 快捷操作 月视图不正常

### ISSUE THREAD

**Issue by zhaiqinglei** [view-design/ViewUI#418]
### Environment
WIN7 / Chrome 80.0 / Vue 2.x

### Reproduction link
[https://run.iviewui.com/gYkDsmEB](https://run.iviewui.com/gYkDsmEB)

### Steps to reproduce
1、将日期初始化成 '2020-03-31' , '2020-04-07' ，
2、打开日期选择面板，点击上一月小图标( < ) 
3、查看 左侧月份 和 右侧 月份。

### What is expected?
左侧显示为2月，右侧显示为3月

### What is actually happening?
左侧仍为3月，右侧显示3月

**Comment by Amanda5293** [comment]
确实这样诶， 老版本的不会呢

**Comment by Amanda5293** [comment]
选择的最小日期为 31 日的，快捷切换上一月都有这个问题

**Comment by djyuning** [comment]
遇到同样的问题！输入框为空时，直接切换月份也会出现左侧和右侧月份一样的问题！😓

**Comment by heerey525** [comment]
现在这个问题还存在，并且datetime更为严重

**Comment by abai1021** [comment]
daterange 下，左边的年切换不到之前的年

**Comment by yang-destiny** [comment]
这个问题现在有解决吗

**Comment by heerey525** [comment]
> 这个问题现在有解决吗

好久没用iview了，感觉文档中split-panels有点效果

**Comment by yang-destiny** [comment]
> > 这个问题现在有解决吗
> 
> 好久没用iview了，感觉文档中split-panels有点效果

那也只是将两边的联动彻底分开，但是问题还是存在就是
