### ISSUE TITLE
[Bug Report][严重]Cascader加上transfer属性后，无法选择

### ISSUE THREAD

**Issue by taojianjian32** [view-design/ViewUI#42]
### Environment
win10/chrome/vue2.0/ivew4.0

### Reproduction link
[https://run.iviewui.com/YMy6tM2w](https://run.iviewui.com/YMy6tM2w)

### Steps to reproduce
1，Cascader加上transfer属性
2，选择某项，点击后立马消失

### What is expected?
正常选择

### What is actually happening?
点击某项后立马消失，未选中

**Comment by taojianjian32** [comment]
![KSkxeA.gif](https://s2.ax1x.com/2019/10/14/KSkxeA.gif)

**Comment by kuangkunpeng** [comment]
怎么解决啊

**Comment by icarusion** [comment]
#32
