### ISSUE TITLE
[Bug Report]表头拖拽事件on-column-width-resize的第一个参数错误

### ISSUE THREAD

**Issue by lifeLikeACode** [view-design/ViewUI#43]
### Environment
所有版本

### Reproduction link
[https://run.iviewui.com/lwZgmBSD](https://run.iviewui.com/lwZgmBSD)

### Steps to reproduce
拖拽头部

### What is expected?
期望结果是newWidth是新的值而不是oldWidth

### What is actually happening?
实际结果newWidth为oldWidth的值

**Comment by icarusion** [comment]
#21
