### ISSUE TITLE
[Bug Report]select 组件 on-clear事件赋值undefined问题

### ISSUE THREAD

**Issue by yangxuehua** [view-design/ViewUI#446]
### Environment
win10/chrome/vue2.6 

### Reproduction link
[https://run.iviewui.com/ccTn8KU4](https://run.iviewui.com/ccTn8KU4)

### Steps to reproduce
在select组件上加上onclear，并在响应方法中对v-model的变量赋一个字符串常值，最后点“提交”针对此变量进行打印，显示undefined

### What is expected?
变量要是显示成此前赋过的值

### What is actually happening?
undefined

**Comment by es5es5** [comment]
SAME ISSUE...!

I faced this problem too, please fix this issue.

I expect just **''** but return **undefined**.

**Comment by CT66** [comment]
升级到4.3.0。开启clearable 属性后依旧还是返回undefined，而不是“”

**Comment by icarusion** [comment]
v-model 必须指定已存在Option的，且在 nextTick
![image](https://user-images.githubusercontent.com/5370542/86422736-86634300-bd10-11ea-8fbc-c7be1158c1ca.png)
