### ISSUE TITLE
[Feature Request]table组件数据量大的时候拖动列会有明显延迟卡顿（100条以上数据）

### ISSUE THREAD

**Issue by Duanxy835** [view-design/ViewUI#49]
### What problem does this feature solve?
表格拖动改变列宽时出现卡顿

### What does the proposed API look like?
数据量大时拖动改变列宽不会出现明显卡顿

**Comment by ForBurning** [comment]
你好， 我在table上添加resizable， 却没有开启拖动列宽功能。   请问还需要做哪些设置吗？（我用的是view-design版本）

**Comment by Duanxy835** [comment]
> 你好， 我在table上添加resizable， 却没有开启拖动列宽功能。 请问还需要做哪些设置吗？（我用的是view-design版本）

你是不是没有设置width，这个必须设置

**Comment by ForBurning** [comment]
嗯 确实是， col必须设置width， 多谢（感觉这样略麻烦）

**Comment by 191895011** [comment]
您好，这个卡顿的问题处理了么？我也遇到该问题，我想用on-column-width-resize触发loading，增加客户使用体验，但当数据多时，该事件也有明显延迟

**Comment by Duanxy835** [comment]
> 您好，这个卡顿的问题处理了么？我也遇到该问题，我想用on-column-width-resize触发loading，增加客户使用体验，但当数据多时，该事件也有明显延迟

没解决，换成element表格了

**Comment by Duanxy835** [comment]
> > 您好，这个卡顿的问题处理了么？我也遇到该问题，我想用on-column-width-resize触发loading，增加客户使用体验，但当数据多时，该事件也有明显延迟
> 
> 没解决，换成element表格了



> 您好，这个卡顿的问题处理了么？我也遇到该问题，我想用on-column-width-resize触发loading，增加客户使用体验，但当数据多时，该事件也有明显延迟

他们iview官方现在都没法解决，太卡了
