### ISSUE TITLE
[Bug Report]项目是没人维护了吧？这么多问题即没人处理，也没人回复

### ISSUE THREAD

**Issue by tengmaoqing** [view-design/ViewUI#508]
### Environment
2.6

### Reproduction link
[https://github.com/view-design/ViewUI/issues](https://github.com/view-design/ViewUI/issues)

### Steps to reproduce
1\2\3

### What is expected?
1\2\3

### What is actually happening?
1\2\3

**Comment by ouzhou** [comment]
你可以试试充值
我已经换成elementUI了
朋友保重

**Comment by tengmaoqing** [comment]
@ouzhou  elementUI最近也是被吐槽回复比较慢。之前的后台项目大量用iview，替换行不通。目前这里面不少bug都不修复，提了PR也不合，实在不行只能自己再维护一版了。

**Comment by NHZEX** [comment]
> @ouzhou elementUI最近也是被吐槽回复比较慢。之前的后台项目大量用iview，替换行不通。目前这里面不少bug都不修复，提了PR也不合，实在不行只能自己再维护一版了。

最近iview遇到性能硬伤，考虑换elementUI了 😂

**Comment by Hotcapsicum** [comment]
之前说是作者全职来搞iview，，希望不是因为经济问题导致的维护过慢

**Comment by NHZEX** [comment]
> > @ouzhou elementUI最近也是被吐槽回复比较慢。之前的后台项目大量用iview，替换行不通。目前这里面不少bug都不修复，提了PR也不合，实在不行只能自己再维护一版了。
> 
> 最近iview遇到性能硬伤，考虑换elementUI了 😂

实践后发现iview遇到的性能问题在el一样存在，只能勉强修复一下用着先了。

**Comment by aoi-umi** [comment]
旧的git主页也没引导到这里，感觉真的没维护了
之前还在这里https://github.com/iview/iview 提来着

**Comment by denzw** [comment]
之前项目是使用JS开发，最近项目升级到TS开发，同时ViewUI升级到4.X版本，但是types还是3.X，反应了三个月都没更新types，造成TS开发体验极差，都想放弃ViewUI使用ElementUI了

**Comment by ouzhou** [comment]
疫情还没过去 会不会是。。。？

**Comment by fangyang921017** [comment]
> 你可以试试充值
> 我已经换成elementUI了
> 朋友保重

难道你不知道 element-ui 不维护了？  我刚刚迁移到了 ant-design-vue

**Comment by hsuan1117** [comment]
> > 你可以试试充值
> > 我已经换成elementUI了
> > 朋友保重
> 
> 难道你不知道 element-ui 不维护了？ 我刚刚迁移到了 ant-design-vue

已经不维护了吗？
