### ISSUE TITLE
Select选项Option的label含有\t制表符导致无法选中。

### ISSUE THREAD

**Issue by blank121** [view-design/ViewUI#547]
### Environment
iview4

### Reproduction link
[https://run.iviewui.com/JXDTP9Ww](https://run.iviewui.com/JXDTP9Ww)

### Steps to reproduce
输入n,选中New York，无法选中。

### What is expected?
输入n,选中New York。

### What is actually happening?
输入n,选中New York，无法选中。

**Comment by ssbunny** [comment]
这个问题很久了，只要有 `\` 存在就会有这个 BUG
