### ISSUE TITLE
[Bug Report]表单验证时，Form 内无 Fields 会造成 validate() 永远 pending

### ISSUE THREAD

**Issue by ssbunny** [view-design/ViewUI#554]
### Environment
All

### Reproduction link
[https://run.iviewui.com/huas81cU](https://run.iviewui.com/huas81cU)

### Steps to reproduce
Form 内无 Field 时，调用表单 validate()

### What is expected?
验证通过，或不通过，或给出明确的第三种状态，或抛出 Error 信息。

### What is actually happening?
Promise 处于 pending 状态，无法正常执行后续逻辑。

---
典型的场景是：动态表单项时，用户删除了所有项目，又去点“保存”进而执行了 validate() 。
ViewUI 源代码中直接遍历了 fields，没有处理 reject 的逻辑，导致如果 fields 是空数组，Promise 永远处理 pending 状态，不能进行后续业务代码的执行。虽然可以通过其它手段避免此问题出现，但 ViewUI 如果能给出 Promise 的执行结果（此种情况时无论 ViewUI 的设计者认为是 reject 还是 resolve 均可），更利于业务代码的编写。

**Comment by icarusion** [comment]
#437
