### ISSUE TITLE
异步树表格，第一次展开子级时会全部收缩（有预览代码）

### ISSUE THREAD

**Issue by iamziyue** [view-design/ViewUI#573]
### Environment
QQ浏览器10.6（Chrome内核70）

### Reproduction link
[https://run.iviewui.com/UMt9KvJP](https://run.iviewui.com/UMt9KvJP)

### Steps to reproduce
访问重现链接，点击展开子级，第一次展开会收缩整棵树，第二次正常展开。

### What is expected?
第一次展开不会收缩整棵树。

### What is actually happening?
收缩了，体验不好

**Comment by Mcler520** [comment]
当展开列的时候没有数据时会影响其他列自动展开；体验不友好

**Comment by yanxu-ok** [comment]
确实有这个问题

**Comment by zhangmgithub** [comment]
先点展开一条，在收缩第一条，在展开第二条；此时会把第一条给展开
 此问题希望尽快解决

**Comment by createNewWorld** [comment]
<Col ...><DatePicker ...></DatePicker></Col> 嵌套使用时日期展示异常了
