### ISSUE TITLE
[Bug Report]版本4.3.1-table组件，展开至第二层时，最自动收起当前记录。

### ISSUE THREAD

**Issue by longergithub** [view-design/ViewUI#579]
### Environment
操作系统：windows 10，游览器：chrome v83.0.4103.116，Vue版本：2.5.22

### Reproduction link
[https://run.iviewui.com/fP4YPDLl](https://run.iviewui.com/fP4YPDLl)

### Steps to reproduce
展开第一级，再展开第二级，当前记录会自动收起

### What is expected?
展开第二级数据，当前记录不会收起

### What is actually happening?
展开第二级数据，当前记录收起

**Comment by iamziyue** [comment]
#573 和我提到的BUG一样，6天了还没修复，客户已经快疯了。
