### ISSUE TITLE
[Bug Report]Poptip组件开启transfer属性后点击内容会关闭气泡

### ISSUE THREAD

**Issue by Wu-Zhichao** [view-design/ViewUI#60]
### Environment
win10/chrome 版本 77.0.3865.120（正式版本） （64 位）/vue 2.0 

### Reproduction link
[https://run.iviewui.com/ozli9Bj2](https://run.iviewui.com/ozli9Bj2)

### Steps to reproduce
Poptip组件开启transfer属性后会导致样式穿透，点击气泡中的内容，会关闭气泡

### What is expected?
点击气泡中的内容不会关闭气泡

### What is actually happening?
点击气泡中的内容会关闭气泡

**Comment by MissingNone** [comment]
设置<code>:capture="false"</code>即可

**Comment by icarusion** [comment]
#32

**Comment by psy-core** [comment]
:capture="false"属性为啥不添加到官方文档里啊？我也遇到了相同问题，排查了好久才发现这个issue :crying_cat_face:
