### ISSUE TITLE
[Feature Request]文件夹上传

### ISSUE THREAD

**Issue by a-tony** [view-design/ViewUI#619]
### What problem does this feature solve?
目前iview的文件上传没啥问题，可是，iview尚不支持文件夹上传，这个在管理系统中特别常见，需要做一个文件夹上传

### What does the proposed API look like?
原先的upload组件只要加一些参数配置就可以选择文件夹上传，
参数1：支持文件夹上传
参数2：上传到服务器端包括文件夹名字（这个可以获得文件夹名字，然后程序进行二次处理）

**Comment by icarusion** [comment]
https://github.com/view-design/ViewUI/commit/af8c2e5e5901f28acb4c61045c4d457d84ddb529
