### ISSUE TITLE
[Bug Report]全局配置 capture:false 时候,如果页面存在选择器,Cascader 下拉页面有问题

### ISSUE THREAD

**Issue by weakspark** [view-design/ViewUI#62]
### Environment
谷歌 最新版本,"vue": "^2.5.2",

### Reproduction link
[https://run.iviewui.com/CKcrTT0T](https://run.iviewui.com/CKcrTT0T)

### Steps to reproduce
无

### What is expected?
Cascader 可以下拉正常点击

### What is actually happening?
点击后消失

**Comment by icarusion** [comment]
#32
