### ISSUE TITLE
[Bug Report]疑似文档描述错误

### ISSUE THREAD

**Issue by billycat** [view-design/ViewUI#63]
### Environment
win7/chrome 77/4.0.0

### Reproduction link
[https://www.iviewui.com/components/table#HJ](https://www.iviewui.com/components/table#HJ)

### Steps to reproduce
您好，重现连接显示的内容，是 ViewUI 表格Table  的官网文档，其中在 “合计” 小节中的描述， 
“默认第一行不进行计算，而是显示 合计，设置属性 sum-text 可以自定义文字。”

是否应该为

“默认第一列不进行计算” 呢？

谢谢！

### What is expected?
默认第一列不进行计算

### What is actually happening?
默认第一行不进行计算

**Comment by icarusion** [comment]
是的，已更改，下个版本更新。
