### ISSUE TITLE
[Bug Report]官网组件avatar头像点击后页面假死

### ISSUE THREAD

**Issue by c-unity** [view-design/ViewUI#64]
### Environment
win10家庭版 1903 / 谷歌 版本 77.0.3865.120（正式版本） （64 位）

### Reproduction link
[https://www.iviewui.com/components/avatar](https://www.iviewui.com/components/avatar)

### Steps to reproduce
打开官网点击组件栏 avatar头像，或者直接在地址栏访问https://www.iviewui.com/components/avatar

### What is expected?
正确进入页面

### What is actually happening?
点击组件栏 avatar头像后页面假死，所有交互没有反应

**Comment by icarusion** [comment]
无法复现。
