### ISSUE TITLE
[Bug Report]4.0 最新版本  Cascader  级联菜单  change-on-select  与  trigger 配合使用时 出现BUG  选择后会立刻关闭菜单

### ISSUE THREAD

**Issue by 515656712** [view-design/ViewUI#65]
### Environment
win8  / Chrome 版本 77.0.3865.120（正式版本） （64 位）/ vue ^2.5.2

### Reproduction link
[https://www.iviewui.com/components/cascader](https://www.iviewui.com/components/cascader)

### Steps to reproduce
 <Cascader trigger :data="data" change-on-select></Cascader> 

级联 可以多级 随意选择时， 每点击其中一个 便会关闭下拉菜单，  如果取消使用  trigger 则变回正常 点击时不会关闭下拉菜单

### What is expected?
在使用 trigger  时 选择级联时  不会关闭菜单

### What is actually happening?
这应该是个BUG  只有4.0才有

---
没有了

**Comment by icarusion** [comment]
到 iView Run 提供可复现示例。

**Comment by itwarlock** [comment]
这不是bug好吧.这是我想要的. 点击就表示想选中.. 选中了 窗口不关闭还显示着干什么?

**Comment by 515656712** [comment]
搞错了！~~ 因 新老版本同时 安装在项目里  所以导致了 这个问题！~~~
