### ISSUE TITLE
[Bug Report]vue组件按需引入, 使用tabs组件报错

### ISSUE THREAD

**Issue by lemonxx22** [view-design/ViewUI#674]
### Environment
vue 2.6.11  view-design 4.3.2  

### Reproduction link
[https://run.iviewui.com/WPGFF19E](https://run.iviewui.com/WPGFF19E)

### Steps to reproduce
配合官方webpack脚手架的项目, 使用了babel-plugin-import, 使用Tabs会提示Unknown custom element: <Dropdown> - did you register the component correctly? For recursive components, make sure to provide the "name" option.  虽然会报错, 但是tabs不影响使用, 实际上整个项目只有一个页面, 没有使用Dropdown, 就几行代码, 代码在https://run.iviewui.com/WPGFF19E

### What is expected?
因项目写的有点多了, 不方便拆开来单独放到网络预览

### What is actually happening?
因项目写的有点多了, 不方便拆开来单独放到网络预览

---
虽然会报错, 但是tabs不影响使用, 实际上整个项目只有一个页面, 没有使用Dropdown, 就几行代码, 代码在https://run.iviewui.com/WPGFF19E

**Comment by lucyonegit** [comment]
### 我遇到了一样的问题，经过阅读源码，才发现他Tab组件中有这样一段代码：

\<div class="ivu-tabs-context-menu" :style="contextMenuStyles"\>
            \<Dropdown trigger="custom" :visible="contextMenuVisible" transfer @on-clickoutside="handleClickContextMenuOutside"\>
                \<DropdownMenu slot="list"\>
                    \<slot name="contextMenu"\>\</slot\>
                \</DropdownMenu\\>
            \</Dropdown\>
\</div\>

### 组件内部都没有注册就直接用了，，，这代码质量。。。

**Comment by AscotLove** [comment]
文档只写了全局引用的方法，没写按需引入的方法，这文档质量不行呀

**Comment by AscotLove** [comment]
<div class="ivu-tabs-context-menu" :style="contextMenuStyles">
            <Dropdown trigger="custom" :visible="contextMenuVisible" transfer @on-clickoutside="handleClickContextMenuOutside">
                <DropdownMenu slot="list">
                    <slot name="contextMenu"></slot>
                </DropdownMenu>
            </Dropdown>
        </div>
自己的ui库，自己不声明组件，要我们帮改代码吗
