### ISSUE TITLE
[Bug Report]表格添加显示合计行show-summary，在表格有滚动条下合计行显示在滚动条下面

### ISSUE THREAD

**Issue by lalaCoding** [view-design/ViewUI#68]
### Environment
Win10/Chrome 77.0.3865.120（正式版本） （64 位）

### Reproduction link
[https://run.iviewui.com/ixRxEl5V](https://run.iviewui.com/ixRxEl5V)

### Steps to reproduce
表格组件上添加合计行属性show-summary为true；表格表头数据colData每列width都设定了值且合计width大于表格width属性值条件下表格带有横向滚动条而且显示在合计行上。

### What is expected?
横向滚动条在合计行下

### What is actually happening?
横向滚动条在合计行上

**Comment by icarusion** [comment]
就是这样设计的。
