### ISSUE TITLE
[Bug Report]当Select 开启 filterable 并且和 OptionGroup 一起使用时的Bug.

### ISSUE THREAD

**Issue by 1600063003** [view-design/ViewUI#728]
### Environment
mac 10.15.7/Google Chrome 86.0.4240.111/Vue 4.4.0

### Reproduction link
[https://run.iviewui.com/vqpeG0mK](https://run.iviewui.com/vqpeG0mK)

### Steps to reproduce
1.选择其中的某项。
2.鼠标离开。
3.再次点击，可选列表里面只显示了当前选中的这项。
4.不使用OptionGroup直接用Option的情况下，不会有这个现象。

### What is expected?
再次点击时默认显示所有的可选列表。

### What is actually happening?
再次点击时可选列表里面只显示了当前选中的这项。

---
1.直接用Option不分组的情况下，再次点击是会默认显示所有的可选列表的。
2.如果默认不显示所有的可选列表，用户每次都需要将一个一个字符全部删除后，其他可选列表才会显示，体验特差。

**Comment by dellenshang** [comment]
https://github.com/view-design/ViewUI/pull/757

不知道会不会合并哈，已经好了

**Comment by 1600063003** [comment]
谢谢
