### ISSUE TITLE
[Feature Request]主题定制

### ISSUE THREAD

**Issue by lotherli** [view-design/ViewUI#74]
![20191021112846](https://user-images.githubusercontent.com/36142693/67174770-f9808f80-f3f5-11e9-995f-0b03c097fe2b.png)
### What problem does this feature solve?
可以在ivieiw ui 中修改颜色 大小等并方便查看， 如element ui里面主题定制功能
https://element.eleme.io/#/zh-CN/theme

### What does the proposed API look like?
是在网页端直接修改颜色，文字大小 ， 边框，圆角等小细节功能

**Comment by icarusion** [comment]
无此计划。
