### ISSUE TITLE
[Bug Report]富文本编辑器组件--选择内容添加超链接，提示框被遮盖显示不全

### ISSUE THREAD

**Issue by flamingoTwoWings** [view-design/ViewUI#746]
### Environment
windows/谷歌

### Reproduction link
[https://adminpro.iviewui.com/editor/quill](https://adminpro.iviewui.com/editor/quill)

### Steps to reproduce
给靠左的内容添加超链接

### What is expected?
提示框靠文本编辑器左侧

### What is actually happening?
提示框会超出文本编辑器

**Comment by icarusion** [comment]
富文本是 quill，查看对应文档和配置。
