### ISSUE TITLE
[Bug Report]1、	级联组件--直接搜索叶子节点，搜索框和搜索结果中间离得比较远

### ISSUE THREAD

**Issue by flamingoTwoWings** [view-design/ViewUI#747]
### Environment
windows10/谷歌 86.0.4240.183

### Reproduction link
[https://run.iviewui.com/bUYLSq0E](https://run.iviewui.com/bUYLSq0E)

### Steps to reproduce
搜索

### What is expected?
搜索的结果挨着cascader框

### What is actually happening?
搜索的结果和cascader框有距离

**Comment by icarusion** [comment]
![image](https://user-images.githubusercontent.com/5370542/98657928-665a2500-237d-11eb-93aa-74b67f0cdb2b.png)
