### ISSUE TITLE
[Bug Report]Select component 'default-label' prop，If this property is set asynchronously, it will not take effect

### ISSUE THREAD

**Issue by Fighter1125** [view-design/ViewUI#751]
### Environment
vue 2.x, chrome 86.x

### Reproduction link
[https://run.iviewui.com/tb3qSetG](https://run.iviewui.com/tb3qSetG)

### Steps to reproduce
created() {
        setTimeout(() => {
            this.model19 = 'beijing'
            this.defaultLabel = '北京'
        }, 1000)
},

### What is expected?
show default label

### What is actually happening?
it's not take effect

**Comment by Fighter1125** [comment]
solution： watch the change of ‘defaultLabel’ in mounted function  https://run.iviewui.com/X9XofqAx

 mounted() {
    this.$refs.select.$watch('defaultLabel', newVal => {
      // console.log('watch', newVal)
      this.$refs.select.query = newVal
    })
    setTimeout(() => {
      this.model19 = 'beijing'
      this.defaultLabel = '北京'
    }, 3000);
  },

**Comment by Simon7520** [comment]
现在遇到了这个问题，远程搜索默认值有bug,组件v-model绑定值和defaultLabel是异步获取的，此时初始值会使用v-model值调接口查询，暂时使用了很曲折的办法，通过Promise阻断, setQuery(defaultLabel),在获取options数据之后，再将v-model绑定值赋值；尝试过看源码修改，但涉及的点和坑太多放弃了，不知道兄弟们有没有好的解决办法；
还有一个办法是Select组件使用v-if=“绑定值”，default-label="异步获取的label数据"，异步获取绑数据后再渲染，这样解决代码简单，但是不确定有没有意外情况。

**Comment by Simon7520** [comment]
感觉最好的办法还是要实现这种效果：设置默认值时第一次不发起请求，直接使用传进去的默认值，现在无论怎样都会发起请求
