### ISSUE TITLE
[Bug Report]select内存泄漏

### ISSUE THREAD

**Issue by webTianyong** [view-design/ViewUI#771]
### Environment
win10 google vue2

### Reproduction link
[http://v1.iviewui.com/components/select](http://v1.iviewui.com/components/select)

### Steps to reproduce
A/B/C  三个spa页面，分别用了select，未使用keepalive  来回切换，内存一直增

### What is expected?
内存释放

### What is actually happening?
内存溢出

**Comment by icarusion** [comment]
https://github.com/view-design/ViewUI/commit/6ee13b133ad6d0b6a5c4259601b019bf72f0824a
