### ISSUE TITLE
tree组件渲染不及时，treeData数据更新后，页面有时候不能及时渲染

### ISSUE THREAD

**Issue by stick777** [view-design/ViewUI#967]
![image](https://user-images.githubusercontent.com/52347319/133596455-639be861-2ba3-4bd0-b69d-cd75c80e0fc6.png)
![image](https://user-images.githubusercontent.com/52347319/133596551-326cd87c-606e-4788-a015-2180b915e143.png)
log打印checked是true，页面上渲染不上去，强制刷新也没用，点击展开数据显示就正常了，感觉是tree组件的渲染bug

**Comment by stick777** [comment]
或者有没有能刷新tree的方法

**Comment by stick777** [comment]
已解决

**Comment by followfire** [comment]
怎么解决的，我也遇到这种问题了

**Comment by Chen1k** [comment]
> 怎么解决的，我也遇到这种问题了

用$set就可以了

**Comment by Chen1k** [comment]
用$set就行了
