### ISSUE TITLE
DatePicker组件有BUG

### ISSUE THREAD

**Issue by LWD8** [view-design/ViewUI#97]
![image](https://user-images.githubusercontent.com/28432674/67657523-f3f4ed80-f991-11e9-9c4d-10716060fd00.png)

上图可见，官方的demo
<DatePicker type="datetime" placeholder="Select date and time" style="width: 200px"></DatePicker>

选择下个月同一天时，时间会不变。并且无法选择。前后的当月今天日期都会标注个小点。
![image](https://user-images.githubusercontent.com/28432674/67657612-3d453d00-f992-11e9-83ba-d240776376c2.png)

**Comment by aralynn** [comment]
因为这两个28号是同一天，都是10月28号

**Comment by LWD8** [comment]
> 因为这两个两个号是同一天，都是10月28号

不是同一天。比如你今天10月28号，然后你选择11月28号时，你会出现我第一张图的情况。

如果什么都不选择，刷新页面，弹窗日期框，会看到前后1个月的28号，都会有默认选中的小圈

**Comment by aralynn** [comment]
> > 因为这两个两个号是同一天，都是10月28号
> 
> 不是同一天。比如你今天10月28号，然后你选择11月28号时，你会出现我第一张图的情况。
> 
> 如果什么都不选择，刷新页面，弹窗日期框，会看到前后1个月的28号，都会有默认选中的小圈

![image](https://user-images.githubusercontent.com/48630455/67660203-2a823680-f999-11e9-9e02-4ce7e3d63614.png)

![image](https://user-images.githubusercontent.com/48630455/67660270-5ef5f280-f999-11e9-8471-b4d71c8d22b4.png)

**Comment by LWD8** [comment]
> > > 因为这两个两个号是同一天，都是10月28号
> > 
> > 
> > 不是同一天。比如你今天10月28号，然后你选择11月28号时，你会出现我第一张图的情况。
> > 如果什么都不选择，刷新页面，弹窗日期框，会看到前后1个月的28号，都会有默认选中的小圈
> 
> ![image](https://user-images.githubusercontent.com/48630455/67660203-2a823680-f999-11e9-9e02-4ce7e3d63614.png)
> 
> ![image](https://user-images.githubusercontent.com/48630455/67660270-5ef5f280-f999-11e9-8471-b4d71c8d22b4.png)

.....................我XXX，还真是，妈啊。对电脑多，脑子都不好使了....现在看你一下看懂了
